
included:
  - {{cookiecutter.app_name}}
excluded:
  - Pods
  - {{cookiecutter.app_name}}/Other/R.generated.swift  
  - {{cookiecutter.app_name}}/Common/ThirdParty

whitelist_rules:
  - array_init
  - attributes 
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_end_indentation
  - closure_parameter_position
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - cyclomatic_complexity
  - discouraged_direct_init
  - discouraged_object_literal
  - discouraged_optional_boolean
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_length
  - file_name
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - identical_operands
  - implicit_getter
  - implicit_return
  - inert_defer
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_random
  - let_var_whitespace
  - line_length
  - mark
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nesting
  - number_separator
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_first_last
  - sorted_imports
  - statement_position
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - todo
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - type_name
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_import
  - unused_setter_value
  - vertical_parameter_alignment
  - vertical_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - type_body_length

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  ProjectName
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} PixelPlex\. All rights reserved\.
                    \/\/
identifier_name:
  excluded:
    - id

line_length: 
  warning: 150

file_length: 
  warning: 750
  error: 1000

type_body_lenght:
  warning: 400
  error: 450

large_tuple: 10

function_body_length: 
  warning: 56
  error: 65

function_parameter_count:
  warning: 10
  error: 15
