platform :ios, '9.0'
use_frameworks!

def swinject_pods
    pod 'Swinject', '2.5.0'
end

def helpers_pods
    pod 'R.swift', '5.0.0'
    pod 'Moya', '12.0.1'
    pod 'SwiftyJSON', '4.2.0'
end

target '{{cookiecutter.app_name}}' do
        
    swinject_pods
    helpers_pods
    
end
